#ifndef HBOS_USER_LIBC_LINUX_FUTEX_H
#define HBOS_USER_LIBC_LINUX_FUTEX_H

#define FUTEX_WAIT             0
#define FUTEX_WAKE             1
#define FUTEX_WAIT_BITSET      9
#define FUTEX_WAKE_BITSET     10
#define FUTEX_PRIVATE_FLAG   128
#define FUTEX_CLOCK_REALTIME 256
#define FUTEX_BITSET_MATCH_ANY 0xffffffffU
#define FUTEX_WAIT_PRIVATE    (FUTEX_WAIT | FUTEX_PRIVATE_FLAG)
#define FUTEX_WAKE_PRIVATE    (FUTEX_WAKE | FUTEX_PRIVATE_FLAG)

#endif
