; HBOS built-in HPT repository — embedded via .incbin, same pattern as
; tcc_headers_blob.asm. build/hpt-repo.bin bundles the local package index
; (Packages) and its payloads (pool/*.hax), generated by tools/genhpt_manifest.py
; + HPT/tools/hpt_repo.py + tools/genhptblob.py. At boot src/tools/hpt_repo_seed.c
; unpacks it into ramfs at /packages so `run hpt list/install/remove` work
; out of the box against the apps already bundled in the image.
section .rodata
bits 64

%ifndef HBOS_BUILD_DIR
%define HBOS_BUILD_DIR "build"
%endif
%strcat HBOS_HPT_REPO_PATH HBOS_BUILD_DIR, "/hpt-repo.bin"

global _binary_build_hpt_repo_bin_start
_binary_build_hpt_repo_bin_start:
incbin HBOS_HPT_REPO_PATH

global _binary_build_hpt_repo_bin_end
_binary_build_hpt_repo_bin_end:
