; HBOS TinyCC sysinclude header bundle — embedded via .incbin, same pattern
; as tcc_runtime_blob.asm. build/tcc/headers.bin is a manifest of all of
; HBOS's user-mode libc headers (src/user/libc/*.h + sys/*.h), generated by
; tools/genheaders.py, written into ramfs at boot (see
; src/tools/tcc_runtime_seed.c) so `tcc foo.c -o foo` can resolve
; `#include <stdio.h>` etc. — HBOS has no persistent /usr/include tree.
section .rodata
bits 64

global _binary_build_tcc_headers_bin_start
_binary_build_tcc_headers_bin_start:
incbin "build/tcc/headers.bin"

global _binary_build_tcc_headers_bin_end
_binary_build_tcc_headers_bin_end:
