; HBOS built-in web vendor bundle (Vue 2.6 runtime, ...) — embedded via .incbin,
; same pattern as tcc_headers_blob.asm / hpt_repo_blob.asm.  build/web-vendor.bin
; is generated by tools/genwebblob.py from third_party/web-vendor/ and unpacked
; into ramfs /system at boot by src/tools/web_vendor_seed.c, so the browser's
; js.hax pipeline can always find a Vue runtime (window.Vue) without fetching
; it over the network.
section .rodata
bits 64

%ifndef HBOS_BUILD_DIR
%define HBOS_BUILD_DIR "build"
%endif
%strcat HBOS_WEB_VENDOR_PATH HBOS_BUILD_DIR, "/web-vendor.bin"

global _binary_build_web_vendor_bin_start
_binary_build_web_vendor_bin_start:
incbin HBOS_WEB_VENDOR_PATH

global _binary_build_web_vendor_bin_end
_binary_build_web_vendor_bin_end:
