; ============================================================
; CJK Font Binary — Embedded via .incbin
; Generated by tools/genhzk.py from ZhengGeDianHei-16.ttf
; ============================================================

section .rodata
align 16

global _binary_build_font_cjk_bin_start
_binary_build_font_cjk_bin_start:
incbin "build/font_cjk.bin"

global _binary_build_font_cjk_bin_end
_binary_build_font_cjk_bin_end: