#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#include "font_cjk.h"
#include "graphics.h"

// ============================================================
// CJK font table — linked by linker symbols
// The binary blob is generated by tools/genhzk.py
// ============================================================

static const uint8_t *g_font_data = NULL;
static uint32_t g_font_count = 0;
static const uint32_t *g_codepoints = NULL; // array of count uint32_t
static const uint8_t  *g_bitmaps = NULL;    // count * 32 bytes

bool cjk_font_init(void) {
    // Get embedded binary range from linker symbols
    extern const uint8_t _binary_build_font_cjk_bin_start[];
    extern const uint8_t _binary_build_font_cjk_bin_end[];

    g_font_data = _binary_build_font_cjk_bin_start;
    size_t total_size = (size_t)(_binary_build_font_cjk_bin_end - _binary_build_font_cjk_bin_start);

    if (total_size < 8) return false;

    // Verify magic
    if (g_font_data[0] != 'H' || g_font_data[1] != 'Z' ||
        g_font_data[2] != 'K' || g_font_data[3] != 'H') {
        return false;
    }

    // Parse header
    g_font_count = *(const uint32_t *)(g_font_data + 4);
    g_codepoints = (const uint32_t *)(g_font_data + 8);
    g_bitmaps    = g_font_data + 8 + g_font_count * 4;

    return true;
}

uint32_t cjk_font_get_count(void) {
    return g_font_count;
}

const uint8_t* cjk_font_lookup(uint32_t codepoint) {
    if (!g_font_data || g_font_count == 0) return NULL;

    // Binary search on sorted codepoint array
    int lo = 0, hi = (int)g_font_count - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        uint32_t cp = g_codepoints[mid];
        if (cp == codepoint) {
            return g_bitmaps + (uint64_t)mid * CJK_GLYPH_BYTES;
        } else if (cp < codepoint) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return NULL; // not found
}

// ============================================================
// Pixel-level glyph rendering helpers
// ============================================================

// Draw a 16×16 CJK glyph at pixel position (x, y) on the framebuffer.
// Draws directly using fb_put_pixel; only works in framebuffer mode
// (not VGA text mode).
void cjk_draw_glyph(uint64_t x, uint64_t y, const uint8_t *bitmap,
                    uint32_t fg_color, uint32_t bg_color) {
    for (int row = 0; row < CJK_GLYPH_SIZE; row++) {
        uint8_t byte0 = bitmap[row * 2];
        uint8_t byte1 = bitmap[row * 2 + 1];
        for (int col = 0; col < 8; col++) {
            fb_put_pixel(x + col, y + row,
                (byte0 & (0x80 >> col)) ? fg_color : bg_color);
            fb_put_pixel(x + 8 + col, y + row,
                (byte1 & (0x80 >> col)) ? fg_color : bg_color);
        }
    }
}

// Get glyph width in character columns (1=half, 2=full width)
int cjk_glyph_width(uint32_t codepoint) {
    if (is_cjk_codepoint(codepoint) || codepoint == 0x3000) {
        return 2; // full-width
    }
    // Some fullwidth forms
    if ((codepoint >= 0xFF01 && codepoint <= 0xFF60) ||
        (codepoint >= 0xFFE0 && codepoint <= 0xFFE6)) {
        return 2;
    }
    return 1; // half-width
}

// ============================================================
// Framebuffer raw pixel manipulation (accessing flanterm's buffer)
// ============================================================

// We need to know the framebuffer address, pitch, and bpp.
// These are retrieved from graphics.c's fb_get_info().
// The fb_put_pixel function in graphics.c handles this.

// For fg/bg color values we use the flanterm context's current colors.
// Graphics.c provides console_set_fg/bg which sets ANSI color codes.
// The actual pixel colors depend on the ANSI palette.

// Default CJK colors
static uint32_t cjk_fg = 0xAAAAAA; // light gray
static uint32_t cjk_bg = 0x000000; // black

void cjk_set_fg(uint32_t color) { cjk_fg = color; }
void cjk_set_bg(uint32_t color) { cjk_bg = color; }
uint32_t cjk_get_fg(void) { return cjk_fg; }
uint32_t cjk_get_bg(void) { return cjk_bg; }