; ============================================================
; Desktop Wallpaper Binary — Embedded via .incbin
; Generated by tools/genwall.py from photo/壁纸.jpg
; ============================================================

section .rodata
align 16

global _binary_build_gui_wall_bin_start
_binary_build_gui_wall_bin_start:
incbin "build/gui_wall.bin"

global _binary_build_gui_wall_bin_end
_binary_build_gui_wall_bin_end:
