#ifndef GUI_WALL_H
#define GUI_WALL_H

#include <stdint.h>
#include <stdbool.h>

// Desktop wallpaper (raw 32-bit pixels, generated by tools/genwall.py and
// embedded via gui_wall.asm). The compositor cover-fits this to the screen.

// Parse the embedded blob. Safe to call repeatedly. False if missing/malformed.
bool gui_wall_init(void);

// Returns the pixel buffer (0x00RRGGBB, row-major) and its dimensions, or NULL.
const uint32_t *gui_wall_pixels(int *w, int *h);

#endif // GUI_WALL_H
