; ============================================================
; Desktop Wallpaper Binary — Embedded via .incbin
; Generated by tools/genwall.py from photo/wallpaper.jpg
; ============================================================

section .rodata
align 16

%ifndef HBOS_BUILD_DIR
%define HBOS_BUILD_DIR "build"
%endif
%strcat HBOS_GUI_WALL_PATH HBOS_BUILD_DIR, "/gui_wall.bin"

global _binary_build_gui_wall_bin_start
_binary_build_gui_wall_bin_start:
incbin HBOS_GUI_WALL_PATH

global _binary_build_gui_wall_bin_end
_binary_build_gui_wall_bin_end:
