#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#include "gui_font.h"

// ============================================================
// GUI font blob — embedded via linker symbols (see gui_glyph.asm).
// Generated by tools/genfont.py. Format documented in that script and
// gui_font.h. Records are 16 bytes, sorted by codepoint for binary search.
// ============================================================

#define GUI_FONT_REC_BYTES 16

static const uint8_t *g_blob = NULL;
static uint32_t       g_count = 0;
static const uint8_t *g_table = NULL;    // glyph records
static const uint8_t *g_bitmaps = NULL;  // coverage section
static uint16_t       g_line_height = 0;
static uint16_t       g_ascent = 0;

static inline uint32_t rd_u32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint16_t rd_u16(const uint8_t *p) {
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}

bool gui_font_init(void) {
    extern const uint8_t _binary_build_gui_font_bin_start[];
    extern const uint8_t _binary_build_gui_font_bin_end[];

    if (g_blob) return true; // already initialized

    const uint8_t *data = _binary_build_gui_font_bin_start;
    size_t total = (size_t)(_binary_build_gui_font_bin_end -
                            _binary_build_gui_font_bin_start);
    if (total < 16) return false;
    if (data[0] != 'G' || data[1] != 'F' || data[2] != 'N' || data[3] != '1')
        return false;

    g_count = rd_u32(data + 4);
    g_line_height = rd_u16(data + 8);
    g_ascent = rd_u16(data + 10);
    g_table = data + 16;

    size_t table_bytes = (size_t)g_count * GUI_FONT_REC_BYTES;
    if (16 + table_bytes > total) return false;
    g_bitmaps = g_table + table_bytes;
    g_blob = data;
    return true;
}

int gui_font_line_height(void) { return g_line_height; }
int gui_font_ascent(void) { return g_ascent; }

bool gui_font_lookup(uint32_t codepoint, gui_glyph_t *out) {
    if (!g_blob || g_count == 0 || !out) return false;

    int lo = 0, hi = (int)g_count - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        const uint8_t *rec = g_table + (size_t)mid * GUI_FONT_REC_BYTES;
        uint32_t cp = rd_u32(rec);
        if (cp == codepoint) {
            uint32_t off = rd_u32(rec + 4);
            out->width     = rec[8];
            out->height    = rec[9];
            out->bearing_x = (int8_t)rec[10];
            out->bearing_y = (int8_t)rec[11];
            out->advance   = rec[12];
            out->coverage  = (out->width && out->height)
                                 ? g_bitmaps + off : NULL;
            return true;
        } else if (cp < codepoint) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return false;
}
