#ifndef GUI_FONT_H
#define GUI_FONT_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================
// GUI proportional anti-aliased font (generated by tools/genfont.py)
// 8-bit grayscale coverage glyphs with per-glyph metrics, laid out on a
// shared baseline. Used by the GUI compositor; the TUI keeps font_cjk.
// ============================================================

typedef struct {
    uint8_t        width;      // coverage bitmap width  (px)
    uint8_t        height;     // coverage bitmap height (px)
    int8_t         bearing_x;  // left side bearing from the pen (px)
    int8_t         bearing_y;  // top of glyph above the baseline (px, +up)
    uint8_t        advance;    // pen advance (px)
    const uint8_t *coverage;   // width*height bytes, row-major (NULL if empty)
} gui_glyph_t;

// Parse the embedded blob. Safe to call more than once. Returns false if the
// blob is missing or malformed.
bool gui_font_init(void);

// Recommended vertical advance between text lines (px). 0 until initialized.
int gui_font_line_height(void);

// Distance from the top of a line box down to the baseline (px).
int gui_font_ascent(void);

// Look up a codepoint. Returns true and fills *out on success. Whitespace
// glyphs return true with out->coverage == NULL and a valid advance.
bool gui_font_lookup(uint32_t codepoint, gui_glyph_t *out);

#endif // GUI_FONT_H
