; ============================================================
; GUI Font Binary — Embedded via .incbin
; Generated by tools/genfont.py from HarmonyOS_Sans_SC_Regular.ttf
; Anti-aliased proportional atlas used by the GUI compositor.
; ============================================================

section .rodata
align 16

%ifndef HBOS_BUILD_DIR
%define HBOS_BUILD_DIR "build"
%endif
%strcat HBOS_GUI_FONT_PATH HBOS_BUILD_DIR, "/gui_font.bin"

global _binary_build_gui_font_bin_start
_binary_build_gui_font_bin_start:
incbin HBOS_GUI_FONT_PATH

global _binary_build_gui_font_bin_end
_binary_build_gui_font_bin_end:
