#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#include "gui_font.h"

// ============================================================
// GUI font blob — embedded via linker symbols (see gui_glyph.asm).
// Generated by tools/genfont.py. "GFN2" format: a size directory followed by
// per-size glyph tables (16-byte records, sorted by codepoint) + bitmaps.
// ============================================================

#define GUI_FONT_REC_BYTES 16
#define GUI_FONT_MAX_SIZES 4

typedef struct {
    uint16_t       px;
    uint16_t       line_height;
    uint16_t       ascent;
    uint32_t       count;
    const uint8_t *table;    // count records
    const uint8_t *bitmaps;  // coverage section
} gui_font_size_t;

static const uint8_t  *g_blob = NULL;
static gui_font_size_t g_sizes[GUI_FONT_MAX_SIZES];
static int             g_nsizes = 0;

static inline uint32_t rd_u32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint16_t rd_u16(const uint8_t *p) {
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}

bool gui_font_init(void) {
    extern const uint8_t _binary_build_gui_font_bin_start[];
    extern const uint8_t _binary_build_gui_font_bin_end[];

    if (g_blob) return true;

    const uint8_t *data = _binary_build_gui_font_bin_start;
    size_t total = (size_t)(_binary_build_gui_font_bin_end -
                            _binary_build_gui_font_bin_start);
    if (total < 8) return false;
    if (data[0] != 'G' || data[1] != 'F' || data[2] != 'N' || data[3] != '2')
        return false;

    uint32_t nsz = rd_u32(data + 4);
    if (nsz == 0 || nsz > GUI_FONT_MAX_SIZES) return false;
    if (8 + nsz * 20 > total) return false;

    for (uint32_t i = 0; i < nsz; i++) {
        const uint8_t *e = data + 8 + i * 20;
        gui_font_size_t *s = &g_sizes[i];
        s->px          = rd_u16(e + 0);
        s->line_height = rd_u16(e + 2);
        s->ascent      = rd_u16(e + 4);
        s->count       = rd_u32(e + 8);
        uint32_t table_off  = rd_u32(e + 12);
        uint32_t bitmap_off = rd_u32(e + 16);
        if (table_off > total || bitmap_off > total) return false;
        if (table_off + (size_t)s->count * GUI_FONT_REC_BYTES > total) return false;
        s->table   = data + table_off;
        s->bitmaps = data + bitmap_off;
    }
    g_nsizes = (int)nsz;
    g_blob = data;
    return true;
}

int gui_font_size_count(void) { return g_nsizes; }

int gui_font_size_px(int idx) {
    if (idx < 0 || idx >= g_nsizes) return 0;
    return g_sizes[idx].px;
}
int gui_font_line_height_n(int idx) {
    if (idx < 0 || idx >= g_nsizes) return 0;
    return g_sizes[idx].line_height;
}
int gui_font_ascent_n(int idx) {
    if (idx < 0 || idx >= g_nsizes) return 0;
    return g_sizes[idx].ascent;
}

bool gui_font_lookup_n(uint32_t codepoint, int idx, gui_glyph_t *out) {
    if (!g_blob || !out || idx < 0 || idx >= g_nsizes) return false;
    const gui_font_size_t *s = &g_sizes[idx];
    if (s->count == 0) return false;

    int lo = 0, hi = (int)s->count - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        const uint8_t *rec = s->table + (size_t)mid * GUI_FONT_REC_BYTES;
        uint32_t cp = rd_u32(rec);
        if (cp == codepoint) {
            uint32_t off = rd_u32(rec + 4);
            out->width     = rec[8];
            out->height    = rec[9];
            out->bearing_x = (int8_t)rec[10];
            out->bearing_y = (int8_t)rec[11];
            out->advance   = rec[12];
            out->coverage  = (out->width && out->height)
                                 ? s->bitmaps + off : NULL;
            return true;
        } else if (cp < codepoint) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return false;
}

int gui_font_line_height(void) { return gui_font_line_height_n(0); }
int gui_font_ascent(void) { return gui_font_ascent_n(0); }
bool gui_font_lookup(uint32_t codepoint, gui_glyph_t *out) {
    return gui_font_lookup_n(codepoint, 0, out);
}
