; ============================================================
; GUI Font Binary — Embedded via .incbin
; Generated by tools/genfont.py from HarmonyOS_Sans_SC_Regular.ttf
; Anti-aliased proportional atlas used by the GUI compositor.
; ============================================================

section .rodata
align 16

global _binary_build_gui_font_bin_start
_binary_build_gui_font_bin_start:
incbin "build/gui_font.bin"

global _binary_build_gui_font_bin_end
_binary_build_gui_font_bin_end:
