#ifndef GUI_FONT_H
#define GUI_FONT_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================
// GUI proportional anti-aliased font (generated by tools/genfont.py).
// Multiple baked pixel sizes (size 0 = base, size 1 = 2x for crisp large text);
// 8-bit grayscale coverage with per-glyph metrics on a shared baseline.
// Used by the GUI compositor; the TUI keeps font_cjk.
// ============================================================

typedef struct {
    uint8_t        width;      // coverage bitmap width  (px)
    uint8_t        height;     // coverage bitmap height (px)
    int8_t         bearing_x;  // left side bearing from the pen (px)
    int8_t         bearing_y;  // top of glyph above the baseline (px, +up)
    uint8_t        advance;    // pen advance (px)
    const uint8_t *coverage;   // width*height bytes, row-major (NULL if empty)
} gui_glyph_t;

// Parse the embedded blob. Safe to call repeatedly. False if missing/malformed.
bool gui_font_init(void);

// Number of baked sizes, and per-size metrics.
int gui_font_size_count(void);
int gui_font_size_px(int idx);
int gui_font_line_height_n(int idx);
int gui_font_ascent_n(int idx);

// Look up a codepoint in a given size. Whitespace returns true with
// out->coverage == NULL and a valid advance.
bool gui_font_lookup_n(uint32_t codepoint, int idx, gui_glyph_t *out);

// Convenience wrappers for the base size (index 0).
int gui_font_line_height(void);
int gui_font_ascent(void);
bool gui_font_lookup(uint32_t codepoint, gui_glyph_t *out);

#endif // GUI_FONT_H
