#ifndef GUI_ICONS_H
#define GUI_ICONS_H

#include <stdint.h>
#include <stdbool.h>

// Flat anti-aliased GUI icon atlas (RGBA tiles, generated by tools/genicon.py
// and embedded via gui_iconsimg.asm). Each icon is a square tile the compositor
// bilinearly scales to the size it needs and alpha-blends onto the surface.

// Icon ids — MUST match the ICONS[] order in tools/genicon.py.
enum {
    ICON_FILES = 0,
    ICON_DISK,
    ICON_SYS,
    ICON_APPS,
    ICON_NOTES,
    ICON_CALC,
    ICON_UWC,
    ICON_SNAKE,
    ICON_BROWSER,
    ICON_CODE,
    ICON_TERM,
    ICON_CLOCK,
    ICON_COUNT
};

// Parse the embedded blob. Safe to call repeatedly. False if missing/malformed.
bool gui_icons_init(void);

// Returns the RGBA pixels (0xAARRGGBB, row-major) for icon `id` and its side
// length in *tile, or NULL if unavailable / id out of range.
const uint32_t *gui_icon_tile(int id, int *tile);

#endif // GUI_ICONS_H
