; ============================================================
; GUI Icon Atlas Binary — Embedded via .incbin
; Generated by tools/genicon.py (flat anti-aliased RGBA tiles).
; NB: base name differs from gui_icons.c so the two don't compile to the
; same .o and silently collide.
; ============================================================

section .rodata
align 16

global _binary_build_gui_icons_bin_start
_binary_build_gui_icons_bin_start:
incbin "build/gui_icons.bin"

global _binary_build_gui_icons_bin_end
_binary_build_gui_icons_bin_end:
