; ============================================================
; GUI Icon Atlas Binary — Embedded via .incbin
; Generated by tools/genicon.py (flat anti-aliased RGBA tiles).
; NB: base name differs from gui_icons.c so the two don't compile to the
; same .o and silently collide.
; ============================================================

section .rodata
align 16

%ifndef HBOS_BUILD_DIR
%define HBOS_BUILD_DIR "build"
%endif
%strcat HBOS_GUI_ICONS_PATH HBOS_BUILD_DIR, "/gui_icons.bin"

global _binary_build_gui_icons_bin_start
_binary_build_gui_icons_bin_start:
incbin HBOS_GUI_ICONS_PATH

global _binary_build_gui_icons_bin_end
_binary_build_gui_icons_bin_end:
