#!/usr/bin/env python3
"""Escape a JavaScript source file into a C string literal header for
embedding (used for third_party/quickjs/hbos_dom.js → build/quickjs/
hbos_dom_inc.h).  Escapes backslash, quote, control chars and NUL;
the JS is embedded as one "..." literal per line so diffs stay readable.
"""
import sys
from pathlib import Path


def main():
    src = Path(sys.argv[1]).read_bytes()
    out = Path(sys.argv[2])
    lines = []
    lines.append(("/* Generated by tools/genjsheader.py from %s - do not edit. */"
                  % sys.argv[1]).encode("utf-8"))
    lines.append(b"static const char hbos_dom_js[] =")
    parts = []
    for raw_line in src.split(b"\n"):
        esc = []
        for b in raw_line:
            if b == 0x5c:
                esc.append(b"\\\\")
            elif b == 0x22:
                esc.append(b'\\"')
            elif b == 0x0a:
                esc.append(b"\\n")
            elif b == 0x0d:
                esc.append(b"\\r")
            elif b == 0x09:
                esc.append(b"\\t")
            elif 0x20 <= b < 0x7f:
                esc.append(bytes([b]))
            else:
                esc.append(("\\x%02x" % b).encode())
        parts.append(b'"' + b"".join(esc) + b'\\n"')
    lines.append(b"\n".join(parts))
    lines.append(b";")
    out.write_bytes(b"\n".join(lines) + b"\n")
    print("[genjsheader] %s -> %s (%d bytes)" % (sys.argv[1], sys.argv[2], len(src)))


if __name__ == "__main__":
    main()
